
// USER REQUESTS
POST http://localhost:1234/account
Content-Type: application/json

{
    "firstname": "Enrico",
    "lastname": "Massias",
    "email": "enrico@espana.fr",
    "password": "yop",
    "passwordConfirmation": "yop",
    "country": "espagne"
}

###
PUT http://localhost:1234/account/15
Content-Type: application/json

{
    "country": "france"
}


###
DELETE http://localhost:1234/account/13
Content-Type: application/json

###
// WALLET REQUESTS

POST http://localhost:1234/wallet
Content-Type: application/json

{
    "name": "long term investment"
}

###
PATCH http://localhost:1234/wallet/19
Content-Type: application/json

{
    "is_default": true
}

###
DELETE http://localhost:1234/wallet/15
Content-Type: application/json

###
// EVENT REQUESTS

POST http://localhost:1234/event/new/15
Content-Type: application/json

{
    "type": "BUY",
    "date": "2020-11-12 12:56:43.435891+01",
    "quantity": 2,
    "total_amount": 32000,
    "platform_sending": "binance",
    "platform_receiving": "binance",
    "currency_asset": "bitcoin",
    "currency_counterparty": "dollar"
}