
// USER REQUESTS
POST http://localhost:1234/account
Content-Type: application/json

{
    "firstname": "Mila",
    "lastname": "Baro",
    "email": "msa@stgely.fr",
    "password": "yop",
    "passwordConfirmation": "yop"
}

###
PUT http://localhost:1234/account/16
Content-Type: application/json

{
    "country": "france"
}


###
DELETE http://localhost:1234/account/13
Content-Type: application/json

###

// LOGIN
POST http://localhost:1234/login
Content-Type: application/json

{
    "email": "jeanb@crypto.io",
    "password": "@Cryptomaniac1"
}

###
// WALLET REQUESTS


###
GET http://localhost:1234/wallet/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjA3NTkwODUwfQ.bw0lhjXptPVzWwlULDy0-cZMLvdrWUESFaWlxPSMx2I

###
POST http://localhost:1234/wallet
Content-Type: application/json

{
    "name": "short term investment"
}

###
PATCH http://localhost:1234/wallet/21
Content-Type: application/json

{
    "name": "short term investment"
}

###
DELETE http://localhost:1234/wallet/15
Content-Type: application/json

###
// EVENT REQUESTS

POST http://localhost:1234/event/new/21
Content-Type: application/json

{
    "type": "buy",
    "date": "2020-11-12 12:56:43.435891+01",
    "total_amount": 20000,
    "quantity": 1.07,
    "platform_sending": "binance",
    "platform_receiving": "binance",
    "currency_asset": "bitcoin",
    "currency_counterparty": "euro"
}

###
PATCH http://localhost:1234/event/95
Content-Type: application/json

{
    "unit_price": 20000
}

###
DELETE http://localhost:1234/event/65
Content-Type: application/json